application: appnamehere
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon.ico
  static_files: images/favicon.png
  upload: images/favicon.png

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: content/images

- url: /other
  static_dir: content/other

- url: .*  # This regex directs all routes to main.app
  script: app.main.app

libraries:
- name: jinja2
  version: latest
