/* @flow */
export default {
  CHANGE_EXPLORER: 'CHANGE_EXPLORER',
  CHANGE_TEST_MESSAGE: 'CHANGE_TEST_MESSAGE',

  START_DRAG: 'START_DRAG',
  STOP_DRAG: 'STOP_DRAG',
  DROP_ANSWER: 'DROP_ANSWER',
  DROP_CLUE: 'DROP_CLUE',

  RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
  SEND_MESSAGE: 'SEND_MESSAGE',

  FETCH_MESSAGES_BY_GROUP: 'FETCH_MESSAGES_BY_GROUP',
  FETCH_MESSAGES_BY_STORY: 'FETCH_MESSAGES_BY_STORY',
}
