application: look-go
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon.ico
  static_files: images/favicon.png
  upload: images/favicon.png

- url: /static
  static_dir: ../dist

- url: .*
  script: app.main.app

libraries:
- name: jinja2
  version: latest
