application: look-go
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon.ico
  static_files: images/favicon.png
  upload: images/favicon.png

- url: /js
  static_dir: ../dist/js

- url: /css
  static_dir: ../dist/css

- url: /assets
  static_dir: ../dist/assets

- url: /api/.*
  script: app.main.app

- url: /.*
  static_files: ../dist/index.html
  upload: ../dist/index.html

libraries:
- name: jinja2
  version: latest
